### ISSUE TITLE
Cloud deployment - Fail to deploy on vexxhost

### ISSUE THREAD

**Issue by sim51** [medialab/hyphe-browser#150]
By choosing vexxhost cloud provider and its data-center based in Canada, at the end of the process (ie. when clicking on the deploy button), I have an error message.

This is the console error : 

```
Something went wrong while deploying the server r: Fail to find image with name Debian GNU/Linux 9 (stretch) [2019-04-09]
    at new r (webpack-internal:///./node_modules/openstack-client/lib/openstack-client.min.js:1:4974)
    at eval (webpack-internal:///./node_modules/openstack-client/lib/openstack-client.min.js:1:117995)
    at c (webpack-internal:///./node_modules/openstack-client/lib/openstack-client.min.js:1:92732)
    at Generator.eval [as _invoke] (webpack-internal:///./node_modules/openstack-client/lib/openstack-client.min.js:1:92485)
    at Generator.forEach.t.(anonymous function) [as next] (webpack-internal:///./node_modules/openstack-client/lib/openstack-client.min.js:1:93089)
    at c (webpack-internal:///./node_modules/openstack-client/lib/openstack-client.min.js:1:100737)
    at u (webpack-internal:///./node_modules/openstack-client/lib/openstack-client.min.js:1:100940)
    at <anonymous>
```

The defined debian image in configuration is not found.
Perhaps it's due to the selected datacenter ... or the image name has changed.

**Comment by sim51** [comment]
Indeed on the canadian data-center, the debian image doesn't the same name.
It's `Debian GNU/Linux 9 (stretch) [2019-03-03]` instead of `Debian GNU/Linux 9 (stretch) [2019-04-09]` ...

We need to test to remove the date part of the name in the hybro config. 
By reading the code of hybro & openstack client, it should work.
